#
# Format:
#
# <heroku_san shorthand name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production:
  app: hundreddaychallenge
  stack: cedar
  config:
    BUNDLE_WITHOUT: "development:test"
